### ISSUE TITLE
Replace hardcoded reference to "variable"

### ISSUE THREAD

**Issue by agouy** [tercen/debarcoding_cytof_operator#3]
Operator is failing when row factor is not names "variable".

There seems to be a hardcoded reference to variable [here](https://github.com/tercen/debarcoding_cytof_operator/blob/37152a28f35c32a3969c59fb93309993ea10e249/op_functions.R#L77 )

**Comment by tsmonteiro** [comment]
@agouy It seems the issue is fixed, though the unit test is not running on github actions. In any case, Myrto can install the latest commit (63e9e19) and use it in the presentation. I have tested her data on my instance with 1 cpu and 16000000000 ram as the env settings and it ran fine. Tomorrow I will check why it is still failing due to memory resources.

**Comment by makostadima** [comment]
@tsmonteiro I ran the debarcoding operator using the latest commit (as instructed above) and it ran fine. I faced issues though downstream.

My workflow can be found here: https://tercen.com/FCF_Tercen/w/2b21e7581f5a8dcd58290987ce2608cf/ds/219bc30a-5370-44b4-abdd-4d2f119f9127

There seems to be an issue with the relations created between filename, Barcodes, channel_name and Scaled.

https://user-images.githubusercontent.com/1746464/230048820-b4052f21-7b33-410b-88c5-cbd522c65556.mp4

As you can see there is no way I can group the events based on the Barcodes.

I thought that this might be ralated to the issue you're facing with the unit test.

FYI when a user tried running it on a much larger dataset Tercen goes down!

**Comment by tsmonteiro** [comment]
I have tested a couple of datasets with commit number 8408c2f , including the EMPA full panel dataset and is both running and resulting in an expected projection downstream. Could you please try this one out, @makostadima ?

The github action issue remains, though.

![image](https://user-images.githubusercontent.com/10157888/230091739-5d4855ce-751f-4709-933e-ba998f10ebe1.png)

**Comment by makostadima** [comment]
@tsmonteiro thanks for the update. I'll test it as soon as I can and I will let you know. Sorry to hear about the unit tests.

**Comment by makostadima** [comment]
@tsmonteiro for me the problem persists on Tercen.com when running commit [8408c2f](https://github.com/tercen/debarcoding_cytof_operator/commit/8408c2fb76e0a932aea5a8e1d7f9e21263fba1a4).

Check the output of the debarcoding step here:

It's missing the `event_id` factor that you actually seem to have in your output.

![image](https://user-images.githubusercontent.com/1746464/230149769-daa0ff95-f806-46ad-aafa-b49079bf0310.png)

On the larger dataset (check this [workflow](https://tercen.com/FCF_Tercen/w/e50efaa75416f1b61950d47b8634647a)) it doesn't even run.

**Comment by tsmonteiro** [comment]
I see. That is the dataset I used to run the test locally. 

I tried setting the cpu (1) and memory (16GB) parameters in tercen.com, but it seems there is some more general issue going on, because the projection is not even being created. 

On the other hand, with these settings, the operator is running on the stage instance, even though it fails during the Github action (https://stage.tercen.com/tsmonteiro/w/f062cb164c337a519d8cf050c2ab8348/ds/9a1962ef-17fe-4edd-a514-3ca6c92ce3e0).

Is there any difference you notice there from what you are running?

**Comment by agouy** [comment]
There seems to be two independent issues:
* failed unit test seems to be due to the fact that custom memory settings are not read properly. It is possible to install the operator on stage but not through GH Actions. @tsmonteiro to check with @amaurel maybe
* @makostadima we would need to exclude an infuence of the read FSC operator. Could you try reproducing your issue using FCS 1.6? If the issue persists @tsmonteiro will investigate output relations.

**Comment by tsmonteiro** [comment]
@makostadima There is a new version (0.0.5) which runs with github actions and in the stage instance with no problems. It also installs in tercen.com but it fails due to memory limitations.  I believe it is the same data set, because I have copied from there. Are you aware of any memory limits on the user or group in tercen.com?

**Comment by makostadima** [comment]
@tsmonteiro @agouy so the weirdest thing happened. I decided to work with some example data from the CATALYST package and also use the read_FCS operator (v.1.6.0) to try the debarcoding operator (v0.0.5).

I did this firstly within the FCF_Tercen in [this workflow](https://tercen.com/FCF_Tercen/w/fe2eb30572c364e70e2e2e4cc66bc2ad/ds/62b38d08-eb6a-4c03-ad88-7f1b381c9adf)  and the problem persists. The operator runs successfully, BUT the ds0..rowID factor isn't output and there's no way to create in the following data step a data projection between scaled values and Barcodes.

NOW the story becomes weird because I redid everything on my personal team [here](https://tercen.com/makostadima/w/fe2eb30572c364e70e2e2e4cc66e87a6) and everything WORKS AS EXPECTED!!!

What on earth is happening???

**Comment by makostadima** [comment]
Please, ignore my previous comment. I made a mistake in the data protection, I believe. Nothing weird with Tercen (duh 🙄).

I'll retry everything proper as soon as I can and let you know.

**Comment by tsmonteiro** [comment]
That is good to hear.

@agouy I think we can close this issue if @makostadima tests confirm that everything is running well, but perhaps open a new issue regarding the memory. At the moment, I have hard-coded a request for memory resources, and this is why it works now. I still haven't figured out why the environment settings from the app-library is not taking effect though.
